services:
  db:
    image: postgres:16
    container_name: bookpulse_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: bookpulse
      POSTGRES_PASSWORD: bookpulse
      POSTGRES_DB: bookpulse
    ports:
      - "5433:5432"
    volumes:
      - bookpulse_pgdata:/var/lib/postgresql/data

volumes:
  bookpulse_pgdata:
